/*
 * LISTE DES ANIMES "FACILES" ET "MOYENS"
 * --------------------------------------
 * Tout ce qui n'est PAS dans cette liste est automatiquement en DIFFICILE
 * (le reste du catalogue AnimeThemes : des milliers d'openings).
 *
 * Chaque ligne :  E(...) = facile   |   M(...) = moyen
 *   E("Titre affiché en anglais", "slug-animethemes", { options })
 *
 * Options possibles :
 *   aliases : autres noms qu'on peut taper pour trouver l'anime
 *   query   : texte de recherche si le slug ne suffit pas
 *   prefix  : true  (ou ...P)  regroupe AUSSI les arcs / saisons au nom différent
 *             (ex. "Food Wars" + "Food Wars: The Second Plate"). Les saisons du type
 *             "2nd Season", "Part 2", "(2009)"... sont déjà regroupées automatiquement.
 *   keep    : true  (ou ...K)  vieil anime (avant 1996) resté très connu : il n'est pas
 *             rétrogradé d'un cran, contrairement aux autres openings anciens.
 *   ops     : difficulté d'un opening précis, avec le numéro "à la suite" de toutes les saisons.
 *             ex. { 13: "easy", 6: "hard" }  => l'opening 13 est facile, le 6 est difficile.
 *
 * Les numéros d'opening sont continus d'une saison à l'autre : le premier opening de la
 * saison 2 prend le numéro qui suit le dernier de la saison 1.
 *
 * Le classement est un choix humain (époque, popularité de l'anime, notoriété et caractère
 * marquant de l'opening). Rien ne le mesure automatiquement : modifie-le comme tu veux.
 */
const ANIMES = (() => {
  const E = (title, slug, o = {}) => ({ title, slug, tier: 'easy', ...o });
  const M = (title, slug, o = {}) => ({ title, slug, tier: 'medium', ...o });
  const P = { prefix: true };
  const K = { keep: true };

  return [
    /* ================= FACILE ================= */
    E("Bleach", "bleach", { ops: { 4: "medium", 5: "medium", 6: "hard", 7: "hard", 8: "medium", 9: "medium", 10: "hard", 11: "medium", 12: "medium", 14: "medium" } }),
    E("Bleach: Thousand-Year Blood War", "bleach_sennen_kessen_hen", { aliases: ["Bleach TYBW"] }),
    E("Naruto", "naruto"),
    E("Naruto Shippuden", "naruto_shippuuden", { aliases: ["Naruto Shippuuden"] }),
    E("One Piece", "one_piece"),
    E("Dragon Ball", "dragon_ball", K),
    E("Dragon Ball Z", "dragon_ball_z", { ...K, aliases: ["DBZ"] }),
    E("Dragon Ball Super", "dragon_ball_super", { aliases: ["DBS"] }),
    E("Hunter x Hunter (2011)", "hunter_x_hunter_2011", { query: "hunter x hunter", aliases: ["HxH", "Hunter x Hunter"] }),
    E("Death Note", "death_note"),
    E("Fullmetal Alchemist", "fullmetal_alchemist", { query: "fullmetal alchemist", aliases: ["FMA", "Fullmetal Alchemist (2003)"] }),
    E("Fullmetal Alchemist: Brotherhood", "fullmetal_alchemist_brotherhood", { aliases: ["FMAB"] }),
    E("Attack on Titan", "shingeki_no_kyojin", { ...P, aliases: ["Shingeki no Kyojin", "L'Attaque des Titans", "SNK"] }),
    E("Demon Slayer", "kimetsu_no_yaiba", { ...P, aliases: ["Kimetsu no Yaiba"] }),
    E("Jujutsu Kaisen", "jujutsu_kaisen", { ...P, aliases: ["JJK"] }),
    E("My Hero Academia", "boku_no_hero_academia", { ...P, aliases: ["Boku no Hero Academia", "MHA"] }),
    E("Sword Art Online", "sword_art_online", { ...P, aliases: ["SAO"] }),
    E("Tokyo Ghoul", "tokyo_ghoul", P),
    E("One Punch Man", "one_punch_man", { aliases: ["OPM"] }),
    E("Fairy Tail", "fairy_tail", P),
    E("Black Clover", "black_clover"),
    E("Code Geass", "code_geass_hangyaku_no_lelouch", { ...P, query: "code geass", aliases: ["Code Geass: Lelouch of the Rebellion"] }),
    E("Cowboy Bebop", "cowboy_bebop"),
    E("Neon Genesis Evangelion", "neon_genesis_evangelion", { ...K, aliases: ["Evangelion"] }),
    E("Steins;Gate", "steins_gate", { ...P, aliases: ["Steins Gate"] }),
    E("Haikyu!!", "haikyuu", { ...P, aliases: ["Haikyuu"] }),
    E("Chainsaw Man", "chainsaw_man"),
    E("Spy x Family", "spy_x_family"),
    E("Mob Psycho 100", "mob_psycho_100"),
    E("Re:Zero", "re_zero_kara_hajimeru_isekai_seikatsu", { ...P, aliases: ["Re Zero", "Re:Zero kara Hajimeru Isekai Seikatsu"] }),
    E("KonoSuba", "kono_subarashii_sekai_ni_shukufuku_wo", { ...P, aliases: ["Kono Subarashii Sekai ni Shukufuku wo"] }),
    E("Dr. Stone", "dr_stone", { ...P, aliases: ["Dr Stone"] }),
    E("The Promised Neverland", "yakusoku_no_neverland", { aliases: ["Yakusoku no Neverland"] }),
    E("Tokyo Revengers", "tokyo_revengers", P),
    E("Oshi no Ko", "oshi_no_ko", { aliases: ["[Oshi no Ko]"] }),
    E("Bocchi the Rock!", "bocchi_the_rock", { aliases: ["Bocchi"] }),
    E("Frieren: Beyond Journey's End", "sousou_no_frieren", { aliases: ["Sousou no Frieren", "Frieren"] }),
    E("Solo Leveling", "ore_dake_level_up_na_ken", { aliases: ["Ore dake Level Up na Ken"] }),
    E("Dandadan", "dandadan"),
    M("Pokémon", "pokemon", { ...P, ops: { 1: "easy" }, aliases: ["Pokemon"] }),
    M("Digimon Adventure", "digimon_adventure", { ...P, ...K, ops: { 1: "easy" } }),
    M("Detective Conan", "meitantei_conan", { aliases: ["Case Closed", "Meitantei Conan"] }),
    E("JoJo's Bizarre Adventure", "jojo_no_kimyou_na_bouken", { ...P, aliases: ["JoJo", "Jojo no Kimyou na Bouken"] }),
    E("Inuyasha", "inuyasha"),
    E("Gintama", "gintama", P),
    E("Blue Lock", "blue_lock"),
    E("Vinland Saga", "vinland_saga"),
    E("No Game No Life", "no_game_no_life"),
    E("That Time I Got Reincarnated as a Slime", "tensei_shitara_slime_datta_ken", { ...P, aliases: ["Tensura", "Tensei shitara Slime Datta Ken"] }),
    E("Mushoku Tensei", "mushoku_tensei_isekai_ittara_honki_dasu", { ...P, aliases: ["Mushoku Tensei: Jobless Reincarnation"] }),
    E("Cyberpunk: Edgerunners", "cyberpunk_edgerunners"),
    E("Toradora!", "toradora", { aliases: ["Toradora"] }),
    E("Kaguya-sama: Love Is War", "kaguya_sama_wa_kokurasetai", { ...P, query: "kaguya sama wa kokurasetai", aliases: ["Kaguya-sama wa Kokurasetai", "Kaguya sama"] }),
    E("Fire Force", "enen_no_shouboutai", { ...P, aliases: ["Enen no Shouboutai"] }),
    E("The Seven Deadly Sins", "nanatsu_no_taizai", { ...P, aliases: ["Nanatsu no Taizai"] }),
    E("Hell's Paradise", "jigokuraku", { aliases: ["Jigokuraku"] }),
    E("Kaiju No. 8", "kaijuu_8_gou", { aliases: ["Kaiju No 8", "Kaijuu 8 gou"] }),
    E("Violet Evergarden", "violet_evergarden"),
    E("Your Lie in April", "shigatsu_wa_kimi_no_uso", { aliases: ["Shigatsu wa Kimi no Uso"] }),
    E("Puella Magi Madoka Magica", "mahou_shoujo_madoka_magica", { aliases: ["Madoka Magica", "Madoka"] }),
    E("Overlord", "overlord", P),
    E("The Melancholy of Haruhi Suzumiya", "suzumiya_haruhi_no_yuuutsu", { ...P, aliases: ["Haruhi Suzumiya", "Suzumiya Haruhi no Yuuutsu"] }),
    E("Sailor Moon", "bishoujo_senshi_sailor_moon", { ...P, ...K, aliases: ["Bishoujo Senshi Sailor Moon"] }),
    E("Slam Dunk", "slam_dunk", K),
    E("Yu Yu Hakusho", "yuu_yuu_hakusho", { ...K, aliases: ["Yuu Yuu Hakusho"] }),
    E("Gurren Lagann", "tengen_toppa_gurren_lagann", { aliases: ["Tengen Toppa Gurren Lagann"] }),
    E("K-On!", "k_on", { ...P, aliases: ["K-On"] }),
    E("Angel Beats!", "angel_beats", { aliases: ["Angel Beats"] }),
    E("Kill la Kill", "kill_la_kill"),
    E("Darling in the Franxx", "darling_in_the_franxx", { aliases: ["DARLING in the FRANXX"] }),
    E("Parasyte: The Maxim", "kiseijuu_sei_no_kakuritsu", { aliases: ["Kiseijuu", "Parasyte"] }),
    E("Akame ga Kill!", "akame_ga_kill", { aliases: ["Akame ga Kill"] }),
    M("Initial D", "initial_d_first_stage", { ...P, ...K, query: "initial d", aliases: ["Initial D First Stage"] }),
    E("Noragami", "noragami", P),

    /* ================= MOYEN ================= */
    M("Boruto: Naruto Next Generations", "boruto_naruto_next_generations", { aliases: ["Boruto"] }),
    M("Dragon Ball Kai", "dragon_ball_kai"),
    M("Dragon Ball GT", "dragon_ball_gt", { aliases: ["DBGT"] }),
    M("Yu-Gi-Oh! Duel Monsters", "yuu_gi_ou_duel_monsters", { ...P, aliases: ["Yu-Gi-Oh", "Yugioh"] }),
    M("Cardcaptor Sakura", "cardcaptor_sakura", { aliases: ["Card Captor Sakura"] }),
    M("Rurouni Kenshin", "rurouni_kenshin", { ...K, aliases: ["Samurai X", "Kenshin le vagabond"] }),
    M("Samurai Champloo", "samurai_champloo"),
    M("Trigun", "trigun"),
    M("Trigun Stampede", "trigun_stampede"),
    M("Berserk", "berserk"),
    M("Hellsing Ultimate", "hellsing_ultimate", { aliases: ["Hellsing"] }),
    M("Monster", "monster"),
    M("Black Lagoon", "black_lagoon", P),
    M("Elfen Lied", "elfen_lied"),
    M("Deadman Wonderland", "deadman_wonderland"),
    M("Claymore", "claymore"),
    M("Great Teacher Onizuka", "great_teacher_onizuka", { aliases: ["GTO"] }),
    M("Ghost in the Shell: Stand Alone Complex", "koukaku_kidoutai_stand_alone_complex", { query: "koukaku kidoutai stand alone complex", aliases: ["Ghost in the Shell"] }),
    M("Paranoia Agent", "mousou_dairinin"),
    M("Gantz", "gantz"),
    M("Eureka Seven", "koukyoushihen_eureka_seven", { query: "eureka seven", aliases: ["Koukyoushihen Eureka Seven"] }),
    M("Hajime no Ippo", "hajime_no_ippo", P),
    M("Durarara!!", "durarara", { ...P, aliases: ["Durarara"] }),
    M("Baccano!", "baccano", { aliases: ["Baccano"] }),
    M("Psycho-Pass", "psycho_pass", { ...P, aliases: ["Psycho Pass"] }),
    M("Another", "another"),
    M("Higurashi: When They Cry", "higurashi_no_naku_koro_ni", { ...P, aliases: ["Higurashi no Naku Koro ni"] }),
    M("Death Parade", "death_parade"),
    M("Erased", "boku_dake_ga_inai_machi", { aliases: ["Boku dake ga Inai Machi"] }),
    M("Anohana", "ano_hi_mita_hana_no_namae_wo_bokutachi_wa_mada_shiranai", { query: "ano hi mita hana no namae wo bokutachi wa mada shiranai" }),
    M("Hyouka", "hyouka"),
    M("Kakegurui", "kakegurui", P),
    M("Little Witch Academia", "little_witch_academia_tv", { query: "little witch academia" }),
    M("Aldnoah.Zero", "aldnoah_zero", { ...P, aliases: ["Aldnoah Zero"] }),
    M("A Certain Magical Index", "toaru_majutsu_no_index", { ...P, aliases: ["Toaru Majutsu no Index"] }),
    M("A Certain Scientific Railgun", "toaru_kagaku_no_railgun", { ...P, aliases: ["Railgun", "Toaru Kagaku no Railgun"] }),
    M("Date A Live", "date_a_live", P),
    M("Nisekoi", "nisekoi", P),
    M("The Quintessential Quintuplets", "gotoubun_no_hanayome", { ...P, aliases: ["Gotoubun no Hanayome", "5-toubun no Hanayome"] }),
    M("Rent-a-Girlfriend", "kanojo_okarishimasu", { ...P, aliases: ["Kanojo Okarishimasu"] }),
    M("Given", "given"),
    M("Banana Fish", "banana_fish"),
    M("Yuri!!! on Ice", "yuri_on_ice", { aliases: ["Yuri on Ice"] }),
    M("SK8 the Infinity", "sk8_the_infinity", { aliases: ["SK8"] }),
    M("Free!", "free", P),
    M("The Prince of Tennis", "tennis_no_oujisama", { aliases: ["Tennis no Oujisama"] }),
    M("Yowamushi Pedal", "yowamushi_pedal", P),
    M("Ace of Diamond", "diamond_no_ace", { ...P, aliases: ["Diamond no Ace"] }),
    M("Kuroko's Basketball", "kuroko_no_basket", { ...P, aliases: ["Kuroko no Basket"] }),
    M("Cells at Work!", "hataraku_saibou", { ...P, aliases: ["Hataraku Saibou"] }),
    M("Made in Abyss", "made_in_abyss", P),
    M("Dororo", "dororo"),
    M("The God of High School", "god_of_high_school"),
    M("Tower of God", "kami_no_tou", { aliases: ["Kami no Tou"] }),
    M("Kingdom", "kingdom", P),
    M("Golden Kamuy", "golden_kamuy", P),
    M("Shaman King", "shaman_king_2021", { query: "shaman king", aliases: ["Shaman King (2021)"] }),
    M("Katekyo Hitman Reborn!", "katekyoushi_hitman_reborn", { aliases: ["Reborn"] }),
    M("D.Gray-man", "d_gray_man", { ...P, aliases: ["D Gray man"] }),
    M("Magi: The Labyrinth of Magic", "magi_the_labyrinth_of_magic", { ...P, aliases: ["Magi"] }),
    M("Seraph of the End", "owari_no_seraph", { ...P, aliases: ["Owari no Seraph"] }),
    M("Black Butler", "kuroshitsuji", { ...P, aliases: ["Kuroshitsuji"] }),
    M("Blue Exorcist", "ao_no_exorcist", { ...P, aliases: ["Ao no Exorcist"] }),
    M("Soul Eater", "soul_eater"),
    M("Assassination Classroom", "ansatsu_kyoushitsu", { ...P, aliases: ["Ansatsu Kyoushitsu"] }),
    M("Fate/Zero", "fate_zero", { aliases: ["Fate Zero"] }),
    M("Fate/stay night: Unlimited Blade Works", "fate_stay_night_unlimited_blade_works_2014", { query: "fate stay night unlimited blade works", aliases: ["Fate stay night UBW"] }),
    M("Bakemonogatari", "bakemonogatari"),
    M("Nana", "nana"),
    M("Ouran High School Host Club", "ouran_koukou_host_club", { aliases: ["Ouran Koukou Host Club"] }),
    M("Fruits Basket", "fruits_basket_2019", { query: "fruits basket", aliases: ["Fruits Basket (2019)"] }),
    M("Horimiya", "horimiya", P),
    M("Komi Can't Communicate", "komi_san_wa_komyushou_desu", { ...P, aliases: ["Komi-san wa Komyushou desu"] }),
    M("My Dress-Up Darling", "sono_bisque_doll_wa_koi_wo_suru", { aliases: ["Sono Bisque Doll wa Koi wo Suru"] }),
    M("Rascal Does Not Dream of Bunny Girl Senpai", "seishun_buta_yarou_wa_bunny_girl_senpai_no_yume_wo_minai", { ...P, aliases: ["Bunny Girl Senpai"] }),
    M("Classroom of the Elite", "youkoso_jitsuryoku_shijou_shugi_no_kyoushitsu_e", { ...P, aliases: ["Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e"] }),
    M("The Rising of the Shield Hero", "tate_no_yuusha_no_nariagari", { ...P, aliases: ["Tate no Yuusha no Nariagari", "Shield Hero"] }),
    M("Log Horizon", "log_horizon", P),
    M("Food Wars!", "shokugeki_no_souma", { ...P, aliases: ["Shokugeki no Souma", "Food Wars"] }),
    M("Ranking of Kings", "ousama_ranking", { aliases: ["Ousama Ranking"] }),
    M("Mashle", "mashle", { ...P, aliases: ["Mashle: Magic and Muscles"] }),
    M("Wind Breaker", "wind_breaker", P),
    M("Zom 100: Bucket List of the Dead", "zom_100_zombie_ni_naru_made_ni_shitai_100_no_koto", { aliases: ["Zom 100"] }),
    M("Dungeon Meshi", "dungeon_meshi", { aliases: ["Delicious in Dungeon"] }),
    M("The Apothecary Diaries", "kusuriya_no_hitorigoto", { ...P, aliases: ["Kusuriya no Hitorigoto"] }),
    M("Lycoris Recoil", "lycoris_recoil"),
    M("Clannad", "clannad", P),
    M("Sakamoto Days", "sakamoto_days"),
    M("DanMachi", "dungeon_ni_deai_wo_motomeru_no_wa_machigatteiru_darou_ka", { ...P, aliases: ["Is It Wrong to Try to Pick Up Girls in a Dungeon?"] }),
    M("Beastars", "beastars", P),
    M("Dorohedoro", "dorohedoro"),
    M("Grand Blue", "grand_blue", { aliases: ["Grand Blue Dreaming"] }),
    M("The Devil Is a Part-Timer!", "hataraku_maou_sama", { ...P, aliases: ["Hataraku Maou-sama"] }),
    M("Mairimashita! Iruma-kun", "mairimashita_iruma_kun", { ...P, aliases: ["Welcome to Demon School! Iruma-kun"] }),
    M("High School DxD", "high_school_dxd", { ...P, aliases: ["Highschool DxD"] }),
    M("Highschool of the Dead", "highschool_of_the_dead", { aliases: ["HOTD"] }),
    M("To Love-Ru", "to_love_ru", P),
    M("Eyeshield 21", "eyeshield_21"),
    M("Beelzebub", "beelzebub"),
    M("Akudama Drive", "akudama_drive"),
    M("86", "86", { ...P, query: "86 eighty six", aliases: ["86: Eighty-Six", "Eighty-Six"] }),
    M("Vivy: Fluorite Eye's Song", "vivy_fluorite_eyes_song", { aliases: ["Vivy"] }),
    M("Odd Taxi", "odd_taxi"),
    M("Summer Time Rendering", "summertime_render", { aliases: ["Summertime Render"] }),
    M("Re:CREATORS", "re_creators", { aliases: ["Re Creators"] }),
    M("Mushishi", "mushishi", P),
    M("Black Bullet", "black_bullet"),
    M("Danganronpa", "danganronpa_the_animation", { ...P, aliases: ["Danganronpa The Animation"] }),
    M("Accel World", "accel_world"),
    M("Charlotte", "charlotte"),
    M("Plastic Memories", "plastic_memories"),
    M("A Lull in the Sea", "nagi_no_asukara", { aliases: ["Nagi no Asukara"] }),
    M("Sound! Euphonium", "hibike_euphonium", { ...P, aliases: ["Hibike! Euphonium"] }),
    M("Wotakoi: Love Is Hard for Otaku", "wotaku_ni_koi_wa_muzukashii", { aliases: ["Wotakoi"] }),
    M("Ao Haru Ride", "ao_haru_ride"),
    M("Love Live! School Idol Project", "love_live", { ...P, aliases: ["Love Live"] }),
    M("Macross Frontier", "macross_frontier"),
    M("Mobile Suit Gundam SEED", "kidou_senshi_gundam_seed", { ...P, aliases: ["Gundam SEED"] }),
    M("Mobile Suit Gundam: Iron-Blooded Orphans", "kidou_senshi_gundam_tekketsu_no_orphans", { ...P, aliases: ["Gundam IBO"] })
  ];
})();
